<a href="https://colab.research.google.com/github/atharvabhairam/3-Column-Preview-Card-Component/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


##Introduction to Tensors
###Creating Tensors
#PyTorch tensors are created using `torch.tensor()`

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Get tensor back as Python int
scalar.item()

7

In [5]:
#vector
vector=torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
from re import M
# Matrix
Matrix= torch.tensor([[7,8],
                     [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
Matrix.ndim

2

In [10]:
Matrix.shape

torch.Size([2, 2])

In [11]:
Matrix[0]

tensor([7, 8])

In [12]:
Matrix[1]

tensor([ 9, 10])

In [13]:
Tensor=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

In [16]:
#Create a random tensor of size (3, 4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5111, 0.7468, 0.2486, 0.9584],
        [0.4441, 0.7459, 0.3875, 0.1394],
        [0.8226, 0.6743, 0.3162, 0.7843]])

In [17]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [18]:
torch.rand(3, 3)

tensor([[0.1093, 0.1699, 0.5721],
        [0.7506, 0.3275, 0.3222],
        [0.3193, 0.7719, 0.4196]])

In [19]:
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones=torch.ones(size=(5,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

#Creating a range of tensors and tensor-like

In [24]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
torch.__version__

'2.9.0+cu126'

In [26]:
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
float_32_tensor=torch.tensor([3.0, 6.0, 9.0],
                             dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.5770, 0.9840, 0.2108, 0.9355],
        [0.5804, 0.4728, 0.5339, 0.5328],
        [0.8356, 0.8733, 0.5737, 0.0292]])

In [33]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensors: {some_tensor.size}")

tensor([[0.5770, 0.9840, 0.2108, 0.9355],
        [0.5804, 0.4728, 0.5339, 0.5328],
        [0.8356, 0.8733, 0.5737, 0.0292]])
Datatype of tensor: torch.float32
Shape of tensors: <built-in method size of Tensor object at 0x7a098b3d7570>


In [34]:
tensor=torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
tensor=tensor*10
tensor

tensor([10, 20, 30])

In [36]:
tensor-10
tensor

tensor([10, 20, 30])

In [37]:
torch.add(tensor,10)

tensor([20, 30, 40])

In [38]:
torch.matmul(tensor,tensor)

tensor(1400)

In [39]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)


tensor(1400)
CPU times: user 1.3 ms, sys: 0 ns, total: 1.3 ms
Wall time: 1.9 ms


In [40]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 210 µs, sys: 27 µs, total: 237 µs
Wall time: 325 µs


tensor(1400)

In [41]:
tensor_A= torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B=torch.tensor([[7,8],
                       [9,10],
                       [10,11]])



In [42]:
tensor_B.T

tensor([[ 7,  9, 10],
        [ 8, 10, 11]])

In [43]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  32],
        [ 53,  67,  74],
        [ 83, 105, 116]])

In [44]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [10, 11]]),
 torch.Size([3, 2]))

In [45]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 10],
         [ 8, 10, 11]]),
 torch.Size([2, 3]))

In [46]:
print(f"Original shapes:tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A={tensor_A.shape}(same shape as above), tensor_B.T ={tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output=torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes:tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A=torch.Size([3, 2])(same shape as above), tensor_B.T =torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 23,  29,  32],
        [ 53,  67,  74],
        [ 83, 105, 116]])

Output shape: torch.Size([3, 3])


###Finding the min, max, mean, sum, etc (tensor aggregation)

In [47]:
#Create a tensor
x= torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [48]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [49]:
#Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [50]:
#Find mean -note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [51]:
#Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [52]:
###Find the position in tensor that has minimum value with argmin()->returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [53]:
x[0]

tensor(1)

In [54]:
#Find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [55]:
x[9]

tensor(91)

#Reshaping, stacking, squeezing, unsqueezing tensors
*Reshaping - reshapes an input tensor to a defined shape

*View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor

*Stacking- combine multiple tensors on top of each other(vstack) or side by side (hstack)

*Squeeze- removes all `1` dimensions from a tensor

*Unsqueeze- add a `1` dimension to a target tensor

*Permute- Return a view of the input with dimensions permuted (swapped) in a certain way.

In [56]:
#Let's create a tensor
import torch
x=torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [57]:
#Add an extra dimension
x_reshaped=x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [58]:
#Change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
z[:,0]=5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [60]:
x_stacked=torch.stack([x, x, x, x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [61]:
#torch.squeeze()- removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [62]:

x_reshaped.shape

torch.Size([9, 1])

In [63]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
x_reshaped.squeeze().shape

torch.Size([9])

In [65]:
# torch.unsqueeze() - adds a single dimension to get a target tensor at a specfic dim(dimension)

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed}")

#Remove extra dimensions from x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [66]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3)) #[height, width, colour_channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1,1->2,2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


##Indexing (selecting data from tensors)
###Indexing with PyTorch is similar to indexing with Numpy

In [67]:
#Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [68]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [69]:
x[0][0]

tensor([1, 2, 3])

In [70]:
x[0][1]

tensor([4, 5, 6])

In [71]:
x[0][2]

tensor([7, 8, 9])

In [72]:
x[0][0][0]

tensor(1)

In [73]:
x[0][2][2]

tensor(9)

In [74]:
#You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [75]:
x[:,2]

tensor([[7, 8, 9]])

In [76]:
#Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [77]:
#Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]


tensor([5])

In [78]:
#Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & Numpy

## PyTorch tensors & Numpy
Numpy is a popular scientific Python Numerical computing library.
And because of this, PyTorch has functionality to interact with it.

*Data is Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

*Pytorch tensor-> Numpy -> `tensor.numpy()`

In [79]:
# NumPy ↔ PyTorch Memory Sharing (Full Explanation + Code)


import numpy as np
import torch

print("=== 1) NumPy -> PyTorch (torch.from_numpy) ===")

# Create a NumPy array
array = np.arange(1.0, 8.0)

# Convert NumPy array to PyTorch tensor
tensor = torch.from_numpy(array)

print("Original array:", array)
print("Tensor from numpy:", tensor)

# -------------------------------------------------------
# NOTE:
# torch.from_numpy() shares the SAME memory.
# Both point to the same data UNTIL YOU CREATE A NEW ARRAY.
# -------------------------------------------------------

print("\n--- Modify NumPy array OUT-OF-PLACE (array = array + 1) ---")

# OUT-OF-PLACE OPERATION → creates NEW array → breaks connection
array = array + 1

print("Updated array:", array)
print("Tensor remains SAME:", tensor)

# -------------------------------------------------------
# NOTE:
# array = array + 1 creates a NEW array → tensor DOES NOT update.
# -------------------------------------------------------

print("\n--- Modify NumPy array IN-PLACE (array2 += 1) ---")

array2 = np.arange(1.0, 8.0)
tensor2 = torch.from_numpy(array2)

array2 += 1   # IN-PLACE update → shared memory maintained

print("array2 after in-place update:", array2)
print("tensor2 also updates:", tensor2)

# -------------------------------------------------------
# NOTE:
# array2 += 1 updates existing memory → tensor2 ALSO updates.
# -------------------------------------------------------

print("\n=== 2) PyTorch -> NumPy (tensor.numpy()) ===")

# Create a tensor
tensor3 = torch.ones(7)

# Convert to NumPy
numpy_tensor3 = tensor3.numpy()

print("tensor3:", tensor3)
print("numpy_tensor3:", numpy_tensor3)

# -------------------------------------------------------
# NOTE:
# tensor.numpy() shares the SAME memory.
# -------------------------------------------------------

print("\n--- Modify Tensor OUT-OF-PLACE (tensor3 = tensor3 + 1) ---")

tensor3 = tensor3 + 1   # Creates NEW tensor → breaks connection

print("tensor3 updated:", tensor3)
print("numpy_tensor3 unchanged:", numpy_tensor3)

# -------------------------------------------------------
# NOTE:
# tensor3 = tensor3 + 1 creates NEW memory → numpy_tensor3 does NOT update.
# -------------------------------------------------------

print("\n--- Modify Tensor IN-PLACE (tensor4.add_(1)) ---")

tensor4 = torch.ones(7)
numpy_tensor4 = tensor4.numpy()

tensor4.add_(1)   # IN-PLACE update

print("tensor4 after in-place:", tensor4)
print("numpy_tensor4 also updated:", numpy_tensor4)

# -------------------------------------------------------
# NOTE:
# tensor4.add_(1) updates original memory → numpy_tensor4 ALSO updates.
# -------------------------------------------------------

print("\n=== SUMMARY ===")
print("In-place ops keep memory shared (+= , add_()).")
print("Out-of-place ops break the sharing (array + 1, tensor + 1).")


=== 1) NumPy -> PyTorch (torch.from_numpy) ===
Original array: [1. 2. 3. 4. 5. 6. 7.]
Tensor from numpy: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

--- Modify NumPy array OUT-OF-PLACE (array = array + 1) ---
Updated array: [2. 3. 4. 5. 6. 7. 8.]
Tensor remains SAME: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

--- Modify NumPy array IN-PLACE (array2 += 1) ---
array2 after in-place update: [2. 3. 4. 5. 6. 7. 8.]
tensor2 also updates: tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

=== 2) PyTorch -> NumPy (tensor.numpy()) ===
tensor3: tensor([1., 1., 1., 1., 1., 1., 1.])
numpy_tensor3: [1. 1. 1. 1. 1. 1. 1.]

--- Modify Tensor OUT-OF-PLACE (tensor3 = tensor3 + 1) ---
tensor3 updated: tensor([2., 2., 2., 2., 2., 2., 2.])
numpy_tensor3 unchanged: [1. 1. 1. 1. 1. 1. 1.]

--- Modify Tensor IN-PLACE (tensor4.add_(1)) ---
tensor4 after in-place: tensor([2., 2., 2., 2., 2., 2., 2.])
numpy_tensor4 also updated: [2. 2. 2. 2. 2. 2. 2.]

=== SUMMARY ===
In-p

##Reproducbility (trying to take random of random)

In short how neural networks learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data ->again ->again ->again...

To reduce the randomness in neural networks and Pytorch comes the concept of **random seed*

Essentially what the random seed does is "flavour" the randomness.

In [80]:
import torch

#Create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor==random_tensor_B)

tensor([[0.6586, 0.5541, 0.5523, 0.3884],
        [0.1400, 0.4846, 0.0010, 0.9489],
        [0.8081, 0.5120, 0.1995, 0.2847]])
tensor([[0.2132, 0.8295, 0.5130, 0.5440],
        [0.9454, 0.5506, 0.6958, 0.5849],
        [0.9772, 0.5696, 0.0555, 0.3790]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [81]:
#Let's make some random but reproducible tensors
import torch

#Set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [82]:
!nvidia-smi

Sat Jan 10 19:41:09 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

#Check for GPU access with PyTorch

In [83]:
import torch
torch.cuda.is_available()

True

In [84]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [85]:
torch.cuda.device_count()

1

##Putting tensors (and models) on the GPU
#The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.