<a href="https://colab.research.google.com/github/atharvabhairam/3-Column-Preview-Card-Component/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


##Introduction to Tensors
###Creating Tensors
#PyTorch tensors are created using `torch.tensor()`

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python int
scalar.item()

7

In [6]:
#vector
vector=torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
from re import M
# Matrix
Matrix= torch.tensor([[7,8],
                     [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
Matrix.ndim

2

In [11]:
Matrix.shape

torch.Size([2, 2])

In [12]:
Matrix[0]

tensor([7, 8])

In [13]:
Matrix[1]

tensor([ 9, 10])

In [14]:
Tensor=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
Tensor.ndim

3

In [16]:
Tensor.shape

torch.Size([1, 3, 3])

In [17]:
#Create a random tensor of size (3, 4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.3870, 0.3195, 0.8242, 0.7780],
        [0.0062, 0.7592, 0.0546, 0.7135],
        [0.9464, 0.0034, 0.6158, 0.3926]])

In [18]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [19]:
torch.rand(3, 3)

tensor([[0.0551, 0.1956, 0.0443],
        [0.1909, 0.9992, 0.4180],
        [0.8123, 0.1972, 0.4719]])

In [20]:
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones=torch.ones(size=(5,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

#Creating a range of tensors and tensor-like

In [25]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
torch.__version__

'2.9.0+cpu'

In [27]:
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
float_32_tensor=torch.tensor([3.0, 6.0, 9.0],
                             dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.8760, 0.5121, 0.3558, 0.5405],
        [0.0475, 0.3044, 0.0479, 0.3683],
        [0.7459, 0.5227, 0.3730, 0.2611]])

In [34]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensors: {some_tensor.size}")

tensor([[0.8760, 0.5121, 0.3558, 0.5405],
        [0.0475, 0.3044, 0.0479, 0.3683],
        [0.7459, 0.5227, 0.3730, 0.2611]])
Datatype of tensor: torch.float32
Shape of tensors: <built-in method size of Tensor object at 0x78fd132c8910>


In [35]:
tensor=torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [36]:
tensor=tensor*10
tensor

tensor([10, 20, 30])

In [37]:
tensor-10
tensor

tensor([10, 20, 30])

In [38]:
torch.add(tensor,10)

tensor([20, 30, 40])

In [39]:
torch.matmul(tensor,tensor)

tensor(1400)

In [40]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)


tensor(1400)
CPU times: user 807 µs, sys: 973 µs, total: 1.78 ms
Wall time: 2.14 ms


In [41]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.11 ms, sys: 0 ns, total: 1.11 ms
Wall time: 1.15 ms


tensor(1400)

In [42]:
tensor_A= torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B=torch.tensor([[7,8],
                       [9,10],
                       [10,11]])



In [43]:
tensor_B.T

tensor([[ 7,  9, 10],
        [ 8, 10, 11]])

In [44]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  32],
        [ 53,  67,  74],
        [ 83, 105, 116]])

In [45]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [10, 11]]),
 torch.Size([3, 2]))

In [46]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 10],
         [ 8, 10, 11]]),
 torch.Size([2, 3]))

In [47]:
print(f"Original shapes:tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A={tensor_A.shape}(same shape as above), tensor_B.T ={tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output=torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes:tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A=torch.Size([3, 2])(same shape as above), tensor_B.T =torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 23,  29,  32],
        [ 53,  67,  74],
        [ 83, 105, 116]])

Output shape: torch.Size([3, 3])


###Finding the min, max, mean, sum, etc (tensor aggregation)

In [66]:
#Create a tensor
x= torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [67]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [68]:
#Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [69]:
#Find mean -note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [70]:
#Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [72]:
###Find the position in tensor that has minimum value with argmin()->returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [75]:
x[0]

tensor(1)

In [77]:
#Find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [81]:
x[9]

tensor(91)

#Reshaping, stacking, squeezing, unsqueezing tensors
*Reshaping - reshapes an input tensor to a defined shape

*View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor

*Stacking- combine multiple tensors on top of each other(vstack) or side by side (hstack)

*Squeeze- removes all `1` dimensions from a tensor

*Unsqueeze- add a `1` dimension to a target tensor

*Permute- Return a view of the input with dimensions permuted (swapped) in a certain way.

In [85]:
#Let's create a tensor
import torch
x=torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [98]:
#Add an extra dimension
x_reshaped=x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [97]:
#Change the view
z=x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [99]:
z[:,0]=5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))